# Generated by Django 4.0.5 on 2022-06-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todomates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='pup_data',
            new_name='pup_date',
        ),
    ]
