# Generated by Django 4.0.5 on 2022-07-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomates', '0002_rename_pup_data_category_pup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pup_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
