# Generated by Django 4.0.5 on 2022-07-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likelion',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
